### PR TITLE
feat!: different gensecret output and talsecret.yaml inclusion

### PR DESCRIPTION
**Pull request by budimanjojo**
`talhelper gensecret` command will now generate a `talosctl` compatible secret file like in siderolabs/talos#5870
The `--patch-configfile` flag is removed because it's no longer needed.

You can now put a `talsecret.yaml` file and `talhelper` will use that file to generate config for you. The old behaviour of using `talenv.yaml` will still be supported, but I think `talenv.yaml` is more of for variable substitution while `talsecret.yaml` is for cluster secret tokens and keys (it can only be used for that too).

You can migrate to the new `talsecret.yaml` like this:
1. `talhelper gen secret --from-configfile ./clusterconfig/mynode.yaml > talsecret.yaml`
2. Encrypt talsecret.yaml with SOPS.
3. Remove all the `inlinePatch` created by `gensecret --patch-configfile` flag
4. Optionally delete the `talenv.yaml` file.

### CODE REVIEW

**Comment by szinn** [comment]
Looks like a good plan. My expectation would be after following the migration I would have:
- a simpler talconfig.yaml
- a new talsecret.yaml that is encrypted with SOPS

and when I run talhelper genconfig that I would get an identical node.yaml file generated (I have noticed that the cluster.id value seems to change from run to run but I don't think that's actually used in node bringup right?)

Does talhelper do the SOPS decode before calling talosctl?

**Comment by szinn** [comment]
When you have a binary with this let me know - I will run it through some tests to make sure the behaviour is what I would expect and what you want to happen as well.

**Comment by budimanjojo** [comment]
> Looks like a good plan. My expectation would be after following the migration I would have:
> 
>     * a simpler talconfig.yaml
> 
>     * a new talsecret.yaml that is encrypted with SOPS
> 
Yes, you no longer need the ugly `inlinePatch` for secrets anymore.
Yes, like always don't forget to encrypt it yourself, `talhelper` do not encrypt it for you :)
> 
> and when I run talhelper genconfig that I would get an identical node.yaml file generated (I have noticed that the cluster.id value seems to change from run to run but I don't think that's actually used in node bringup right?)
> 
Yes, the config should be identical except now the `cluster.id` will also persists. Not sure if that matters but the generated secret file now have that from the upstream function call.
> Does talhelper do the SOPS decode before calling talosctl?
Yes, the decoded file will be in `/tmp/talsecret.yaml` and it will be cleaned up afterwards so you shouldn't see the file at all.

**Comment by szinn** [comment]
Bring it on!

**Comment by budimanjojo** [comment]
I'll release it tomorrow morning when I'm on my computer again :D

**Comment by szinn** [comment]
I will try this out tomorrow hopefully

**Comment by szinn** [comment]
Works as expected - generated new configs and they match the previous 1.2.0 configs with the exception of the workers which had removed 3 key values. However, talosctl gen config does the same. Blew away a CP node on my staging cluster and then applyconfig with the new generated config and node came up fine and connected in

**Comment by budimanjojo** [comment]
> Works as expected - generated new configs and they match the previous 1.2.0 configs with the exception of the workers which had removed 3 key values. However, talosctl gen config does the same. Blew away a CP node on my staging cluster and then applyconfig with the new generated config and node came up fine and connected in

Awesome, thanks for the test! What were the 3 key values removed in worker config though?

**Comment by szinn** [comment]
Removed from the worker configs:
- machine.ca.key
- cluster.aescbcEncryptionSecret
- cluster.ca.key

I used talosctl to generate a configuration with no patches etc, and it has "" for each of those entries too.

**Comment by budimanjojo** [comment]
> Removed from the worker configs:
> 
>     * machine.ca.key
> 
>     * cluster.aescbcEncryptionSecret
> 
>     * cluster.ca.key
> 
> 
> I used talosctl to generate a configuration with no patches etc, and it has "" for each of those entries too.

Looks like it was generated by the previous version of `talhelper` because of explicitly patching the manifests using `inlinePatch` instead of generating from a call. 

The `generate` package indeed doesn't define the `ca.key` and `cluster.key`:
https://github.com/siderolabs/talos/blob/cdb6bb2cc78685c218506c61a477c8a8e569e861/pkg/machinery/config/types/v1alpha1/generate/worker.go#L81
https://github.com/siderolabs/talos/blob/cdb6bb2cc78685c218506c61a477c8a8e569e861/pkg/machinery/config/types/v1alpha1/generate/worker.go#L43

Thanks for the findings, I didn't even notice it :rofl:

**Comment by szinn** [comment]
Glad I can help - that's what my staging cluster is for - to experiment with

**Pull request merged**
