### PR TITLE
feat: Create Docker Image

### LINKED ISSUE #246: Provide Docker Image
I think it would be helpful to also distribute this in the form of a docker image.

### PR DESCRIPTION
**Pull request by mirceanton**
Fixes #246

### CODE REVIEW

**Comment by mirceanton** [comment]
The image and the pipeline seem to be working. I created a [dummy tag](https://github.com/mirceanton/talhelper/releases/tag/v0.16.0-test) which triggered a [build job](https://github.com/mirceanton/talhelper/actions/runs/7099209899) which in turn published [this image](https://github.com/mirceanton/talhelper/pkgs/container/talhelper)

```bash
mike@NotANuc:~/home-ops/infra/home-cluster$ docker run -e SOPS_AGE_KEY_FILE=/config/age-key.txt -v $(pwd):/config ghcr.io/mirceanton/talhelper:v0.16.0-test genconfig
Unable to find image 'ghcr.io/mirceanton/talhelper:v0.16.0-test' locally
v0.16.0-test: Pulling from mirceanton/talhelper
c926b61bad3b: Already exists 
071ee02e14dc: Pull complete 
a573f4d6c183: Pull complete 
Digest: sha256:cc7b88ae7dbc5d5f48c00ce4677208b6c176ff4b9de55f277df2cb92271adb63
Status: Downloaded newer image for ghcr.io/mirceanton/talhelper:v0.16.0-test
generated config for nuc in ./clusterconfig/home-cluster-nuc.yaml
generated config for srv in ./clusterconfig/home-cluster-srv.yaml
generated config for minisforum in ./clusterconfig/home-cluster-minisforum.yaml
generated client config in ./clusterconfig/talosconfig
generated .gitignore file in ./clusterconfig/.gitignore
```

**Comment by mirceanton** [comment]
nvm the fix was trivial 😆

**Comment by budimanjojo** [comment]
@mirceanton Thanks! I don't think we should have the default value for `SOPS_AGE_KEY_FILE`, I prefer using `SOPS_AGE_KEY` with the value of the secret when running `sops` inside a container. Also `SOPS_AGE_*` is only used for encryption using `age`, there are also PGP, AWS KMS, Vault, AKV, GCP KMS, etc.

**Comment by mirceanton** [comment]
@budimanjojo sometimes, I forget SOPS is not the only option 😂

**Comment by budimanjojo** [comment]
The PR looks good, can u do a `git squash` so I don't push 10 commits at once :D

**Comment by mirceanton** [comment]
I'm not at my computer right now. I'll do that tomorrow morning!

You can squash and merge from GitHub, though, if you want to do it in the meantime.

**Comment by budimanjojo** [comment]
No problem, I can wait :)

**Pull request merged**
