### PR TITLE
fix: secretfile is empty

### LINKED ISSUE #470: invalid memory address or nil pointer dereference when a secretfile is empty
The current code doesn't check if a secret file exists and isn't empty.

```
> talhelper genconfig
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10383033c]

goroutine 1 [running]:
github.com/budimanjojo/talhelper/pkg/talos.NewClusterInput(0x14000456408, {0x10386b0cc, 0x13}, {0x103859c80, 0x5})
    github.com/budimanjojo/talhelper/pkg/talos/input.go:44 +0x1cc
github.com/budimanjojo/talhelper/pkg/generate.GenerateConfig(0x14000456408, 0x0, {0x1038661fa, 0xf}, {0x10386b0cc?, 0x1c?}, {0x103859c80, 0x5}, 0x0)
    github.com/budimanjojo/talhelper/pkg/generate/config.go:23 +0x54
github.com/budimanjojo/talhelper/cmd.init.func7(0x140002b6c00?, {0x104632440?, 0x4?, 0x10385930d?})
    github.com/budimanjojo/talhelper/cmd/genconfig.go:50 +0x2a4
github.com/spf13/cobra.(*Command).execute(0x1045b7ec0, {0x104632440, 0x0, 0x0})
    github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x1045b9000)
    github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
    github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/budimanjojo/talhelper/cmd.Execute(...)
    github.com/budimanjojo/talhelper/cmd/root.go:61
main.main()
    github.com/budimanjojo/talhelper/main.go:10 +0x28
```

### PR DESCRIPTION
**Pull request by M0NsTeRRR**
Fix #470

### CODE REVIEW

**Comment by budimanjojo** [comment]
Thank you @M0NsTeRRR!
I don't know if the fix should be generating with a new secret bundle or error it out nicely to the user.

If you think that generating a new secret bundle is the preferred solution, maybe log it out verbosely too instead of just in the debug mode?
I'm thinking like showing the user: `<filename> is an empty file, generating with this secret: <the secrets>` so the user can populate the empty secret file with them because without .

Or if you think that error it out nicely is the preferred solution, then this will be a lot easier.

**Comment by M0NsTeRRR** [comment]
> Thank you @M0NsTeRRR!
> I don't know if the fix should be generating with a new secret bundle or error it out nicely to the user.
> 
> If you think that generating a new secret bundle is the preferred solution, maybe log it out verbosely too instead of just in the debug mode?
> I'm thinking like showing the user: `<filename> is an empty file, generating with this secret: <the secrets>` so the user can populate the empty secret file with them because without that the new file will be secretless.
> 
> Or if you think that error it out nicely is the preferred solution, then this will be a lot easier.

Your welcome, to be honest I don't use Talos. I've just saw the issue on the k8s discord and as I developper I've looked into 😁. I chose to do that to keep current behavior but maybe thé other way make more sense. Tell me what you prefer and I will update.

**Comment by budimanjojo** [comment]
Ahh I see :smile:
I think catching the error and return error as something like "file is empty" might do it. Also I think you should use `else if` for that so the original `else` statement can stay.

**Comment by M0NsTeRRR** [comment]
Done @budimanjojo :)

**Comment by budimanjojo** [comment]
Thank you!

**Pull request merged**
